<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>BrokenHorizonLauncher</AssemblyName>
    <Product>Broken Horizon Launcher</Product>
  </PropertyGroup>
  <ItemGroup>
    <None Include="launcher-config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
